import type { DiagnosticInput } from "@/lib/RiskCalculator";

export type MockScenario = {
  id: string;
  name: string;
  input: DiagnosticInput;
};

export const DEFAULT_INPUT: DiagnosticInput = {
  nomeEmpresa: "",
  contato: "",
  cnpj: "",
  regimeTributario: "nao_sei",
  setor: "nao_sei",
  porteEmpresa: "nao_sei",
  numeroFuncionarios: 0,
  faturamentoMensal: 0,
  percentualB2B: 0,
  margemPercentual: 20,
  comprasCreditaveisPercentual: 0,
  possuiClientePjRelevante: "nao_sei",
  sistemaFiscalPreparado: "nao_sei",
  possuiDividaFiscal: "nao_sei",
  valorDividaEstimado: 0,
  valorDividaUniao: 0,
  valorDividaEstado: 0,
  valorDividaMunicipio: 0,
  valorDividaOutros: 0,
  possuiCreditoIcms: "nao_sei",
  valorCreditoIcmsEstimado: 0,
  objetivoCliente: "nao_sei",
};

export const MOCK_SCENARIOS: MockScenario[] = [
  {
    id: "simples-b2b-alto",
    name: "Simples + B2B alto",
    input: {
      ...DEFAULT_INPUT,
      nomeEmpresa: "Metal Alpha Simples",
      regimeTributario: "simples",
      setor: "industria",
      porteEmpresa: "media",
      numeroFuncionarios: 48,
      faturamentoMensal: 420000,
      percentualB2B: 82,
      margemPercentual: 12,
      comprasCreditaveisPercentual: 58,
      possuiClientePjRelevante: "sim",
      sistemaFiscalPreparado: "nao",
      possuiDividaFiscal: "nao",
      possuiCreditoIcms: "nao_sei",
      objetivoCliente: "clientes_pj",
    },
  },
  {
    id: "simples-b2c-baixo",
    name: "Simples + B2C baixo risco",
    input: {
      ...DEFAULT_INPUT,
      nomeEmpresa: "Loja Bairro Legal",
      regimeTributario: "simples",
      setor: "comercio",
      porteEmpresa: "pequena",
      numeroFuncionarios: 12,
      faturamentoMensal: 95000,
      percentualB2B: 8,
      margemPercentual: 28,
      comprasCreditaveisPercentual: 40,
      possuiClientePjRelevante: "nao",
      sistemaFiscalPreparado: "sim",
      possuiDividaFiscal: "nao",
      possuiCreditoIcms: "nao",
      objetivoCliente: "nao_sei",
    },
  },
  {
    id: "industria-icms",
    name: "Industria + ICMS informado",
    input: {
      ...DEFAULT_INPUT,
      nomeEmpresa: "Industria Delta",
      regimeTributario: "real",
      setor: "industria",
      porteEmpresa: "grande",
      numeroFuncionarios: 180,
      faturamentoMensal: 1300000,
      percentualB2B: 65,
      margemPercentual: 16,
      comprasCreditaveisPercentual: 72,
      possuiClientePjRelevante: "sim",
      sistemaFiscalPreparado: "parcial",
      possuiDividaFiscal: "nao",
      possuiCreditoIcms: "sim",
      valorCreditoIcmsEstimado: 480000,
      objetivoCliente: "caixa",
    },
  },
  {
    id: "divida-fiscal",
    name: "Empresa com divida fiscal",
    input: {
      ...DEFAULT_INPUT,
      nomeEmpresa: "Servicos Horizonte",
      regimeTributario: "presumido",
      setor: "servicos",
      porteEmpresa: "media",
      numeroFuncionarios: 35,
      faturamentoMensal: 260000,
      percentualB2B: 45,
      margemPercentual: 18,
      comprasCreditaveisPercentual: 18,
      possuiClientePjRelevante: "sim",
      sistemaFiscalPreparado: "nao_sei",
      possuiDividaFiscal: "sim",
      valorDividaEstimado: 350000,
      valorDividaUniao: 260000,
      valorDividaEstado: 65000,
      valorDividaMunicipio: 25000,
      possuiCreditoIcms: "nao",
      objetivoCliente: "certidao",
    },
  },
  {
    id: "servicos-margem-baixa",
    name: "Servicos + margem baixa",
    input: {
      ...DEFAULT_INPUT,
      nomeEmpresa: "Clinica Operacao Enxuta",
      regimeTributario: "presumido",
      setor: "servicos",
      porteEmpresa: "media",
      numeroFuncionarios: 54,
      faturamentoMensal: 310000,
      percentualB2B: 32,
      margemPercentual: 7,
      comprasCreditaveisPercentual: 12,
      possuiClientePjRelevante: "nao_sei",
      sistemaFiscalPreparado: "parcial",
      possuiDividaFiscal: "nao_sei",
      possuiCreditoIcms: "nao",
      objetivoCliente: "imposto_alto",
    },
  },
];
